spring:
  application:
    name: test-quest-api
  # MariaDB
  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_dataBaseName}?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    # properties:
    #     hibernate:
    #       auto_quote_keyword: true

  servlet:
    multipart:
      max-file-size: 10MB  # 단일 파일 최대 크기 (예: 10MB)
      max-request-size: 100MB # 전체 요청 (여러 파일 포함) 최대 크기 (예: 100MB)

# 로그 레벨 (선택)
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

jwt:
  header: Authorization
  expires-in: 86400
  mobile-expires-in: 31536000
  secret-key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs # OpenAPI 문서 경로 변경 (기본: /v3/api-docs)
    enabled: true # API 문서 활성화 (기본: true)
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 접속 경로 (기본: /swagger-ui.html)
    enabled: true # Swagger UI 활성화 (기본: true)
    display-request-duration: true # 요청 시간 표시
    tags-sorter: alpha # 태그 정렬 방식 (alpha: 알파벳순)
    operations-sorter: method # operation 정렬 방식 (method, alpha)

firebase:
  sdk:
    json: |
      {
        "type": "${FIREBASE_TYPE}",
        "project_id": "${FIREBASE_PROJECT_ID}",
        "private_key_id": "${FIREBASE_PRIVATE_KEY_ID}",
        "private_key": "${FIREBASE_PRIVATE_KEY}", # 전체 private_key 문자열을 이 변수에서 가져옵니다.
        "client_email": "${FIREBASE_CLIENT_EMAIL}",
        "client_id": "${FIREBASE_CLIENT_ID}",
        "auth_uri": "${FIREBASE_AUTH_URI}",
        "token_uri": "${FIREBASE_TOKEN_URI}",
        "auth_provider_x509_cert_url": "${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}",
        "client_x509_cert_url": "${FIREBASE_CLIENT_X509_CERT_URL}",
        "universe_domain": "${FIREBASE_UNIVERSE_DOMAIN}"
      }
  storage:
    bucket: ${FIREBASE_BUCKET}